# We download the data from ... and package it up in a set of steps,
# all using the buildAll function from this package

BiocManager::install()
BiocManager::install("getDEE2")
library(Biobase)
library(SummarizedExperiment)
library(getDEE2)
library(devtools)
devtools::install_github(repo="flaviusb/CellScore")
library(CellScore)
library(DESeq2)
devtools::install_github(repo="flaviusb/homosapienDEE2CellScore", force=TRUE)
library(homosapienDEE2CellScore)
BiocManager::install("AnnotationHub")
BiocManager::install("ExperimentHub")
library(AnnotationHub)
library(AnnotationHubData)
library(ExperimentHub)
library(ExperimentHubData)
homosapienDEE2CellScoreData <- buildData(build_tsne=FALSE, build_raw=TRUE, build_srx_agg=TRUE)
BiocManager::install()
BiocManager::install("getDEE2")
library(Biobase)
library(SummarizedExperiment)
library(getDEE2)
library(devtools)
devtools::install_github(repo="flaviusb/CellScore", force=TRUE)
library(CellScore)
library(DESeq2)
devtools::install_github(repo="flaviusb/homosapienDEE2CellScore", force=TRUE)
library(homosapienDEE2CellScore)
BiocManager::install("AnnotationHub")
BiocManager::install("ExperimentHub")
library(AnnotationHub)
library(AnnotationHubData)
library(ExperimentHub)
library(ExperimentHubData)
homosapienDEE2CellScoreData <- buildData(build_tsne=FALSE, build_raw=TRUE, build_srx_agg=TRUE)
BiocManager::install()
BiocManager::install("getDEE2")
library(Biobase)
library(SummarizedExperiment)
library(getDEE2)
library(devtools)
devtools::install_github(repo="flaviusb/CellScore", force=TRUE)
library(CellScore)
library(DESeq2)
devtools::install_github(repo="flaviusb/homosapienDEE2CellScore", force=TRUE)
library(homosapienDEE2CellScore)
BiocManager::install("AnnotationHub")
BiocManager::install("ExperimentHub")
library(AnnotationHub)
library(AnnotationHubData)
library(ExperimentHub)
library(ExperimentHubData)
homosapienDEE2CellScoreData <- buildData(build_tsne=FALSE, build_raw=TRUE, build_srx_agg=TRUE)
writeOutSEZip(homosapienDEE2CellScoreData$qc_pass_raw, filename_base="hsDEE2cs_qc_pass_raw")
writeOutSEZip(homosapienDEE2CellScoreData$qc_warn_raw, filename_base="hsDEE2cs_qc_warn_raw")
writeOutSEZip(homosapienDEE2CellScoreData$qc_pass_agg, filename_base="hsDEE2cs_qc_pass_agg")
writeOutSEZip(homosapienDEE2CellScoreData$qc_warn_agg, filename_base="hsDEE2cs_qc_warn_agg")
writeOutSEZip(homosapienDEE2CellScoreData$qc_pass_deseq2, filename_base="hsDEE2cs_qc_pass_deseq2")
writeOutSEZip(homosapienDEE2CellScoreData$qc_warn_deseq2, filename_base="hsDEE2cs_qc_warn_deseq2")
writeOutSEZip(homosapienDEE2CellScoreData$qc_pass_rank, filename_base="hsDEE2cs_qc_pass_rank")
writeOutSEZip(homosapienDEE2CellScoreData$qc_warn_rank, filename_base="hsDEE2cs_qc_warn_rank")

